name: "vaultwarden-server"
services:
  vaultwarden:
    container_name: vaultwarden
    image: "vaultwarden/server@sha256:84fd8a47f58d79a1ad824c27be0a9492750c0fa5216b35c749863093bfa3c3d7" # vaultwarden 1.34.3 arm64
    restart: "always"
    volumes:
      - "./vw-data:/data"
    environment:
      - DOMAIN=https://${SERVER_DOMAIN}
      - WEBSOCKET_ENABLED=true
      - ROCKET_PORT=80
      - ROCKET_ADDRESS=0.0.0.0
      - LOG_LEVEL=WARN
    ports:
      - 8080:80

  caddy:
    container_name: caddy
    image: "caddy@sha256:87aa104ed6c658991e1b0672be271206b7cd9fec452d1bf3ed9ad6f8ab7a2348" # caddy 2.10.2 - linux/arm64/v8
    restart: "always"
    volumes:
      - "./caddy/caddy-data:/data"
      - "./caddy/conf:/etc/caddy"
      - "./caddy/certs:/certs:ro"
    ports:
      - "443:443"
      - "80:80"
