global:
  scrape_interval: "15s"
  scrape_timeout: "10s"
  evaluation_interval: "1m"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets:
          - prometheus:9090
  - job_name: "node_exporter"
    static_configs:
      - targets:
          - "host.docker.internal:9100"
  - job_name: "cadvisor"
    static_configs:
      - targets: ["host.docker.internal:8080"]
  - job_name: "loki"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["loki:3100"]
